import { describe, expect, it, vi } from 'vitest';
import {
  buildImportResolution,
  classifyPlaybackKind,
  resolveYoutubeSearchQuery,
  resolveYoutubeImportSource,
  viewCountScore,
} from './importResolver.js';
import { extractMetadataFields } from './ytdlpInfo.js';

describe('classifyPlaybackKind', () => {
  it('classifies common YouTube music source shapes', () => {
    expect(classifyPlaybackKind({ title: 'Song (Official Music Video)' })).toBe(
      'youtube-official-mv',
    );
    expect(classifyPlaybackKind({ title: 'Song (Official Audio)' })).toBe(
      'youtube-official-audio',
    );
    expect(classifyPlaybackKind({ title: 'Song Lyric Video' })).toBe(
      'youtube-lyric-video',
    );
    expect(
      classifyPlaybackKind({ title: 'Song', artist: 'Artist - Topic' }),
    ).toBe('youtube-topic-audio');
    expect(
      classifyPlaybackKind(
        { title: 'Song' },
        'https://music.youtube.com/watch?v=dQw4w9WgXcQ',
      ),
    ).toBe('yt-music-source');
  });

  it('uses metadata signals instead of treating every YT Music URL as audio-native', () => {
    expect(
      classifyPlaybackKind(
        {
          title: 'Song (Official Music Video)',
          signals: { variantFlags: ['official-mv'] },
        },
        'https://music.youtube.com/watch?v=dQw4w9WgXcQ',
      ),
    ).toBe('youtube-official-mv');
    expect(
      classifyPlaybackKind({
        title: 'Song',
        artist: 'Artist',
        signals: {
          isAutoGenerated: true,
          isTopicChannel: true,
          hasStructuredTrack: true,
          variantFlags: [],
        },
      }),
    ).toBe('youtube-topic-audio');
  });

  it('treats YT Music Songs evidence as audio-native unless variant evidence is stronger', () => {
    expect(
      classifyPlaybackKind({
        title: 'Song',
        artist: 'Artist',
        searchProvider: 'yt-music',
        signals: { isYoutubeMusicSong: true, variantFlags: [] },
      }),
    ).toBe('yt-music-song');
    expect(
      classifyPlaybackKind({
        title: 'Song (Live)',
        artist: 'Artist',
        searchProvider: 'yt-music',
        signals: { isYoutubeMusicSong: true, variantFlags: ['live'] },
      }),
    ).toBe('youtube-live');
    expect(
      classifyPlaybackKind({
        title: 'Song (Sped Up)',
        artist: 'Artist',
        searchProvider: 'yt-music',
        signals: { isYoutubeMusicSong: true, variantFlags: ['sped-up'] },
      }),
    ).toBe('youtube-variant');
  });

  it.each([
    '雨愛 (氛圍版)',
    '雨爱 (氛围DJ版)',
    '雨爱（R&B版）',
    '雨愛（翻唱）',
    '雨愛（加速版）',
    '雨愛（不插電版）',
  ])(
    'keeps common CJK named variants out of release recordings: %s',
    (title) => {
      expect(
        classifyPlaybackKind({
          title,
          artist: 'Artist - Topic',
          searchProvider: 'yt-music',
          signals: {
            isYoutubeMusicSong: true,
            isTopicChannel: true,
            hasStructuredTrack: true,
            variantFlags: [],
          },
        }),
      ).toBe('youtube-variant');
    },
  );

  it('classifies bare "Official Video" (no "music"/"mv") as an official MV', () => {
    // Regression test: this title shape used to fall through to
    // youtube-other because importResolver's own MV regex was narrower
    // than downloader.js's — now both share musicTitle.js's
    // OFFICIAL_MV_TITLE_RE.
    expect(classifyPlaybackKind({ title: 'Song (Official Video)' })).toBe(
      'youtube-official-mv',
    );
  });
});

describe('resolveYoutubeSearchQuery', () => {
  it('uses a logarithmic views bonus capped below the adjacent recording-kind gap', () => {
    expect(viewCountScore(undefined)).toBe(0);
    expect(viewCountScore(9999)).toBe(0);
    expect(viewCountScore(10000)).toBe(1);
    expect(viewCountScore(1000000)).toBe(3);
    expect(viewCountScore(1000000000)).toBe(6);
    expect(viewCountScore(1000000000000)).toBe(6);
  });

  it('uses views as a weak tie-breaker between otherwise equivalent recordings', async () => {
    const resolution = await resolveYoutubeSearchQuery('Artist Song', {
      searchPlaybackCandidates: vi.fn().mockResolvedValue([
        {
          id: 'low00000001',
          title: 'Song',
          artist: 'Artist',
          duration: 211,
          viewCount: 100,
          playbackKind: 'youtube-official-audio',
        },
        {
          id: 'high0000001',
          title: 'Song',
          artist: 'Artist',
          duration: 211,
          viewCount: 1000000000,
          playbackKind: 'youtube-official-audio',
        },
      ]),
      existingIds: new Set(),
    });

    expect(
      resolution.candidates.map((candidate) => candidate.playbackVideoId),
    ).toEqual(['high0000001', 'low00000001']);
    expect(
      resolution.candidates[0].score - resolution.candidates[1].score,
    ).toBe(6);
  });

  it('ranks the complete bounded pool before returning at most 12 candidates', async () => {
    const ordinaryCandidates = Array.from({ length: 12 }, (_, index) => ({
      id: `o${String(index).padStart(10, '0')}`,
      title: `Unrelated ${index}`,
      artist: 'Channel',
      duration: 211,
      playbackKind: 'youtube-other',
    }));
    const releaseCandidate = {
      id: 'r0000000001',
      title: 'Song',
      artist: 'Artist',
      duration: 211,
      playbackKind: 'yt-music-song',
    };

    const resolution = await resolveYoutubeSearchQuery('Artist Song', {
      searchPlaybackCandidates: vi
        .fn()
        .mockResolvedValue([...ordinaryCandidates, releaseCandidate]),
      existingIds: new Set(),
    });

    expect(resolution.candidates).toHaveLength(12);
    expect(resolution.candidates[0].playbackVideoId).toBe('r0000000001');
    expect(resolution.recommendedCandidate?.playbackVideoId).toBe(
      'r0000000001',
    );
  });

  it('prefers a YT Music Songs recording over the matching YouTube video', async () => {
    const resolution = await resolveYoutubeSearchQuery('Artist Song', {
      searchPlaybackCandidates: vi.fn().mockResolvedValue([
        {
          id: 'mv000000000',
          title: 'Song (Official Music Video)',
          artist: 'Artist',
          duration: 240,
          searchProvider: 'youtube',
          signals: { variantFlags: ['official-mv'] },
        },
        {
          id: 'song0000001',
          title: 'Song',
          artist: 'Artist',
          album: 'Album',
          duration: 211,
          searchProvider: 'yt-music',
          signals: { isYoutubeMusicSong: true, variantFlags: [] },
        },
      ]),
      existingIds: new Set(),
    });

    expect(resolution.recommendedCandidate).toMatchObject({
      playbackVideoId: 'song0000001',
      playbackKind: 'yt-music-song',
      recordingFit: 'release-recording',
      searchProvider: 'yt-music',
    });
  });

  it('does not let a YT Music variant outrank a clean YouTube release recording', async () => {
    const resolution = await resolveYoutubeSearchQuery('Artist Song', {
      searchPlaybackCandidates: vi.fn().mockResolvedValue([
        {
          id: 'fast0000001',
          title: 'Song (Sped Up)',
          artist: 'Artist',
          duration: 170,
          searchProvider: 'yt-music',
          signals: {
            isYoutubeMusicSong: true,
            variantFlags: ['sped-up'],
          },
        },
        {
          id: 'topic000001',
          title: 'Song',
          artist: 'Artist - Topic',
          duration: 211,
          searchProvider: 'youtube',
          signals: {
            isAutoGenerated: true,
            isTopicChannel: true,
            hasStructuredTrack: true,
            variantFlags: [],
          },
        },
      ]),
      existingIds: new Set(),
    });

    expect(resolution.recommendedCandidate).toMatchObject({
      playbackVideoId: 'topic000001',
      playbackKind: 'youtube-topic-audio',
      recordingFit: 'release-recording',
    });
  });

  it('ranks release-like recordings and exposes a download-ready recommendation', async () => {
    const searchPlaybackCandidates = vi.fn().mockResolvedValue([
      {
        id: 'mv000000000',
        title: 'Song (Official Music Video)',
        artist: 'Artist',
        duration: 240,
        playbackKind: 'youtube-official-mv',
      },
      {
        id: 'topic000001',
        title: 'Song',
        artist: 'Artist - Topic',
        duration: 211,
        playbackKind: 'youtube-topic-audio',
      },
    ]);

    await expect(
      resolveYoutubeSearchQuery('Artist Song', {
        searchPlaybackCandidates,
        existingIds: new Set(),
      }),
    ).resolves.toMatchObject({
      inputKind: 'text-query',
      source: null,
      recommendedCandidate: {
        playbackVideoId: 'topic000001',
        recordingFit: 'release-recording',
      },
      downloadInput: 'topic000001',
      needsSourceReview: false,
    });
  });

  it('requires a manual choice when every result is a mismatched variant', async () => {
    const searchPlaybackCandidates = vi.fn().mockResolvedValue([
      {
        id: 'live1234567',
        title: 'Song Live',
        artist: 'Artist',
        duration: 350,
        playbackKind: 'youtube-live',
      },
    ]);

    const resolution = await resolveYoutubeSearchQuery('Artist Song', {
      searchPlaybackCandidates,
      existingIds: new Set(),
    });

    expect(resolution.candidates[0]).toMatchObject({
      recordingFit: 'mismatch',
    });
    expect(resolution.recommendedCandidate).toBe(null);
    expect(resolution.downloadInput).toBe(null);
    expect(resolution.needsSourceReview).toBe(true);
  });

  it('does not preselect a release-like result without a finite duration', async () => {
    const resolution = await resolveYoutubeSearchQuery('Artist Song', {
      searchPlaybackCandidates: vi.fn().mockResolvedValue([
        {
          id: 'topic000001',
          title: 'Song',
          artist: 'Artist - Topic',
          playbackKind: 'youtube-topic-audio',
        },
      ]),
      existingIds: new Set(),
    });

    expect(resolution.candidates[0]).toMatchObject({
      playbackVideoId: 'topic000001',
      recordingFit: 'release-recording',
    });
    expect(resolution.recommendedCandidate).toBe(null);
    expect(resolution.needsSourceReview).toBe(true);
  });

  it.each(['youtube-lyric-video', 'youtube-official-mv'])(
    'keeps a popular %s candidate visible without auto-selecting it',
    async (playbackKind) => {
      const resolution = await resolveYoutubeSearchQuery('Artist Song', {
        searchPlaybackCandidates: vi.fn().mockResolvedValue([
          {
            id: 'video000001',
            title: 'Song',
            artist: 'Artist',
            duration: 211,
            viewCount: 1000000000,
            playbackKind,
          },
        ]),
        existingIds: new Set(),
      });

      expect(resolution.candidates).toHaveLength(1);
      expect(resolution.recommendedCandidate).toBe(null);
      expect(resolution.downloadInput).toBe(null);
      expect(resolution.needsSourceReview).toBe(true);
    },
  );
});

describe('buildImportResolution', () => {
  it('recommends an audio candidate over the pasted official MV source', () => {
    const resolution = buildImportResolution({
      input: 'https://youtube.com/watch?v=mv000000000',
      sourceVideoId: 'mv000000000',
      sourceMetadata: {
        title: 'Actual Artist - Canonical Title (Official Music Video)',
        artist: 'Label Music',
        duration: 260,
        thumbnailUrl: 'https://example.test/mv.jpg',
      },
      playbackCandidates: [
        {
          id: 'aud12345678',
          title: 'Canonical Title',
          artist: 'Actual Artist',
          duration: 211,
          playbackKind: 'yt-music-song',
        },
      ],
      existingIds: new Set(),
    });

    expect(resolution.recommendedCandidate).toMatchObject({
      playbackVideoId: 'aud12345678',
      playbackKind: 'yt-music-song',
      confidence: 'high',
    });
    expect(resolution.source).toMatchObject({
      playbackVideoId: 'mv000000000',
      playbackKind: 'youtube-official-mv',
    });
    expect(resolution.downloadInput).toBe('aud12345678');
    expect(resolution.needsSourceReview).toBe(false);
  });

  it('keeps the pasted source first while ranking the remaining candidates', () => {
    const resolution = buildImportResolution({
      input: 'https://youtube.com/watch?v=mv000000000',
      sourceVideoId: 'mv000000000',
      sourceMetadata: {
        title: 'Actual Artist - Canonical Title (Official Music Video)',
        artist: 'Label Music',
        duration: 260,
      },
      playbackCandidates: [
        {
          id: 'live1234567',
          title: 'Canonical Title Live',
          artist: 'Actual Artist',
          duration: 260,
          playbackKind: 'youtube-live',
        },
        {
          id: 'aud12345678',
          title: 'Canonical Title',
          artist: 'Actual Artist',
          duration: 211,
          playbackKind: 'yt-music-song',
        },
      ],
    });

    expect(
      resolution.candidates.map((candidate) => candidate.playbackVideoId),
    ).toEqual(['mv000000000', 'aud12345678', 'live1234567']);
    expect(resolution.candidates[0]).toMatchObject({
      playbackVideoId: 'mv000000000',
      isSource: true,
    });
    expect(resolution.recommendedCandidate).toMatchObject({
      playbackVideoId: 'aud12345678',
      playbackKind: 'yt-music-song',
    });
  });

  it('keeps the pasted source visible while limiting the candidate list to 12', () => {
    const playbackCandidates = Array.from({ length: 20 }, (_, index) => ({
      id: `a${String(index).padStart(10, '0')}`,
      title: 'Canonical Title',
      artist: 'Actual Artist',
      duration: 211,
      playbackKind: 'yt-music-song',
    }));
    const resolution = buildImportResolution({
      input: 'https://youtube.com/watch?v=mv000000000',
      sourceVideoId: 'mv000000000',
      sourceMetadata: {
        title: 'Canonical Title (Official Music Video)',
        artist: 'Actual Artist',
        duration: 240,
      },
      playbackCandidates,
    });

    expect(resolution.candidates).toHaveLength(12);
    expect(resolution.candidates[0].playbackVideoId).toBe('mv000000000');
    expect(resolution.recommendedCandidate?.playbackVideoId).toBe(
      'a0000000000',
    );
  });

  it('falls back to the source when no better playback candidate exists', () => {
    const resolution = buildImportResolution({
      input: 'https://youtube.com/watch?v=mv000000000',
      sourceVideoId: 'mv000000000',
      sourceMetadata: {
        title: 'Canonical Title (Official Music Video)',
        artist: 'Actual Artist',
        duration: 260,
      },
      existingIds: new Set(['mv000000000']),
    });

    expect(resolution.recommendedCandidate).toMatchObject({
      playbackVideoId: 'mv000000000',
      alreadyDownloaded: true,
    });
    expect(resolution.needsSourceReview).toBe(false);
  });

  it('uses track identity as canonical metadata without dash-splitting track titles', () => {
    const resolution = buildImportResolution({
      input: 'https://music.youtube.com/watch?v=music000001',
      sourceVideoId: 'music000001',
      sourceMetadata: {
        title: 'Seven - Clean Ver. (合作演出：Latto)',
        artist: '정국 (Jung Kook) 和 Latto',
        duration: 184,
      },
      trackIdentity: {
        title: 'Seven - Clean Ver. (合作演出：Latto)',
        artists: ['정국 (Jung Kook)', 'Latto'],
        artist: '정국 (Jung Kook), Latto',
        duration: 184,
        sourcePlatform: 'yt-music',
        sourceType: 'track',
        confidence: 'high',
      },
      playbackCandidates: [
        {
          id: 'music000002',
          title: 'Clean Ver.',
          artist: 'Seven',
          duration: 184,
          playbackKind: 'yt-music-song',
        },
      ],
    });

    expect(resolution.canonical).toMatchObject({
      title: 'Seven - Clean Ver. (合作演出：Latto)',
      artist: '정국 (Jung Kook), Latto',
      duration: 184,
    });
    expect(resolution.source).toMatchObject({
      title: 'Seven - Clean Ver. (合作演出：Latto)',
      artist: '정국 (Jung Kook) 和 Latto',
    });
  });

  it('keeps one row when search returns the pasted source again', () => {
    const resolution = buildImportResolution({
      input: 'https://youtube.com/watch?v=mv000000000',
      sourceVideoId: 'mv000000000',
      sourceMetadata: {
        title: 'Canonical Title (Official Music Video)',
        artist: 'Actual Artist',
        duration: 260,
      },
      playbackCandidates: [
        {
          id: 'mv000000000',
          title: 'Canonical Title (Official Music Video)',
          artist: 'Actual Artist',
          duration: 260,
          playbackKind: 'youtube-official-mv',
        },
      ],
    });

    expect(
      resolution.candidates.filter(
        (candidate) => candidate.playbackVideoId === 'mv000000000',
      ),
    ).toHaveLength(1);
  });

  it('preserves cross-platform provider evidence for same-id candidates', () => {
    const resolution = buildImportResolution({
      input: 'https://youtube.com/watch?v=nR-LSk3LfEA',
      sourceVideoId: 'nR-LSk3LfEA',
      sourceMetadata: {
        title: 'Sabrina Hu - Parachute',
        artist: 'Sabrina Hu',
        duration: 250,
      },
      playbackCandidates: [
        {
          id: 'nR-LSk3LfEA',
          title: 'Parachute',
          artist: 'Sabrina Hu',
          duration: 250,
          playbackKind: 'yt-music-song',
          searchProvider: 'yt-music',
          availableProviders: ['yt-music', 'youtube'],
        },
      ],
    });

    expect(resolution.candidates).toHaveLength(1);
    expect(resolution.candidates[0]).toMatchObject({
      playbackVideoId: 'nR-LSk3LfEA',
      title: 'Sabrina Hu - Parachute',
      isSource: true,
      availableProviders: ['yt-music', 'youtube'],
      playbackKind: 'yt-music-song',
      recordingFit: 'release-recording',
    });
  });
});

describe('resolveYoutubeImportSource', () => {
  it.each([
    ['https://youtube.com/watch?v=mv000000000', 'youtube', 'video'],
    ['https://music.youtube.com/watch?v=mv000000000', 'yt-music', 'track'],
  ])(
    'uses normalized metadata for %s without changing its source identity',
    async (input, sourcePlatform, sourceType) => {
      const sourceMetadata = extractMetadataFields({
        title: '劉若英 René Liu【後來 Later】Official Music Video',
        uploader: '滾石唱片 ROCK RECORDS',
        duration: 341,
      });
      const searchPlaybackCandidates = vi.fn().mockResolvedValue([]);

      const resolution = await resolveYoutubeImportSource(input, {
        extractVideoId: () => 'mv000000000',
        fetchMetadata: vi.fn().mockResolvedValue(sourceMetadata),
        searchPlaybackCandidates,
        existingIds: new Set(),
      });

      expect(resolution).toMatchObject({
        sourceVideoId: 'mv000000000',
        canonical: { title: '後來 Later', artist: '劉若英 René Liu' },
        trackIdentity: {
          title: '後來 Later',
          artist: '劉若英 René Liu',
          sourcePlatform,
          sourceType,
        },
      });
      expect(searchPlaybackCandidates).toHaveBeenCalledWith(
        expect.objectContaining({
          title: '後來 Later',
          artist: '劉若英 René Liu',
          sourcePlatform,
          sourceType,
        }),
        sourceMetadata,
        { sourcePlatform },
      );
    },
  );

  it('uses injected metadata and search providers to resolve a recommended playback id', async () => {
    const fetchMetadata = vi.fn().mockResolvedValue({
      title: 'Actual Artist - Canonical Title (Official Music Video)',
      artist: 'Label Music',
      duration: 260,
    });
    const searchPlaybackCandidates = vi.fn().mockResolvedValue([
      {
        id: 'aud12345678',
        title: 'Canonical Title',
        artist: 'Actual Artist',
        duration: 211,
        playbackKind: 'yt-music-song',
      },
    ]);

    await expect(
      resolveYoutubeImportSource('https://youtube.com/watch?v=mv000000000', {
        extractVideoId: () => 'mv000000000',
        fetchMetadata,
        searchPlaybackCandidates,
        existingIds: new Set(),
      }),
    ).resolves.toMatchObject({
      sourceVideoId: 'mv000000000',
      trackIdentity: {
        title: 'Canonical Title',
        artists: ['Actual Artist'],
        sourcePlatform: 'youtube',
      },
      downloadInput: 'aud12345678',
      recommendedCandidate: {
        playbackVideoId: 'aud12345678',
      },
    });
    expect(fetchMetadata).toHaveBeenCalledWith('mv000000000');
    expect(searchPlaybackCandidates).toHaveBeenCalledWith(
      expect.objectContaining({
        title: 'Canonical Title',
        artists: ['Actual Artist'],
        artist: 'Actual Artist',
        duration: 260,
        sourcePlatform: 'youtube',
        sourceType: 'video',
      }),
      expect.objectContaining({ title: expect.any(String) }),
      { sourcePlatform: 'youtube' },
    );
  });

  it('passes YT Music source platform into playback candidate search', async () => {
    const fetchMetadata = vi.fn().mockResolvedValue({
      title: 'Canonical Title',
      artist: 'Actual Artist',
      duration: 211,
    });
    const searchPlaybackCandidates = vi.fn().mockResolvedValue([]);

    await resolveYoutubeImportSource(
      'https://music.youtube.com/watch?v=music000001',
      {
        extractVideoId: () => 'music000001',
        fetchMetadata,
        searchPlaybackCandidates,
        existingIds: new Set(),
      },
    );

    expect(searchPlaybackCandidates).toHaveBeenCalledWith(
      expect.objectContaining({
        title: 'Canonical Title',
        artists: ['Actual Artist'],
        artist: 'Actual Artist',
        duration: 211,
        sourcePlatform: 'yt-music',
        sourceType: 'track',
      }),
      expect.objectContaining({ title: 'Canonical Title' }),
      { sourcePlatform: 'yt-music' },
    );
  });
});
