'use strict';

const {
  extractTitleDerivedSearchParts,
  looksLikeChannelArtist,
  normalizeText,
} = require('./musicTitle');
const { VIDEO_ID_RE } = require('./youtube');

const AUTO_GENERATED_DESCRIPTION_RE = /\bAuto-generated by YouTube\b/iu;
const STAFF_ROLE_RE =
  /\b(?:arranger|composer|engineer|lyricist|music\s+publisher|producer|songwriter|writer)\b/iu;
const PERFORMING_ROLE_RE = /\b(?:artist|performer|vocalist|vocals?)\b/iu;
const FEATURE_MARKER_RE = /\b(?:feat(?:uring)?|ft)\.?\s+/giu;
const FEATURE_SUFFIX_BRACKET_RE =
  /\s(?=[([\u3010（][^)\]\u3011）}]*(?:official|audio|video|visualizer|lyrics?|remix|mix|live|version|edit|remaster))/iu;
const ARTIST_NAME_BOUNDARY_PATTERN = String.raw`[\s,;|/&×·()[\]{}【】]`;
const BRACKET_CLOSE_BY_OPEN = new Map([
  ['(', ')'],
  ['[', ']'],
  ['{', '}'],
  ['\u3010', '\u3011'],
  ['（', '）'],
]);

function metadataNameKey(value) {
  return normalizeText(value)
    .normalize('NFKC')
    .replace(/\s+/gu, ' ')
    .toLocaleLowerCase();
}

function isHttpsUrl(value) {
  if (typeof value !== 'string') return false;
  try {
    return new URL(value).protocol === 'https:';
  } catch {
    return false;
  }
}

function extractThumbnailUrl(info) {
  if (isHttpsUrl(info.thumbnail)) return info.thumbnail;
  if (Array.isArray(info.thumbnails)) {
    const thumbnailUrl = [...info.thumbnails]
      .reverse()
      .map((thumbnail) => thumbnail?.url)
      .find(isHttpsUrl);
    if (thumbnailUrl) return thumbnailUrl;
  }

  if (typeof info.id === 'string' && VIDEO_ID_RE.test(info.id)) {
    return `https://i.ytimg.com/vi/${info.id}/hqdefault.jpg`;
  }
  return undefined;
}

function normalizedStringList(value) {
  if (!Array.isArray(value)) return [];
  const values = [];
  for (const entry of value) {
    const text = normalizeText(entry);
    const key = metadataNameKey(text);
    if (!key || values.some((current) => current.key === key)) continue;
    values.push({ key, text });
  }
  return values;
}

function creditRoleKeys(description) {
  const empty = { performing: new Set(), staff: new Set() };
  if (
    typeof description !== 'string' ||
    !AUTO_GENERATED_DESCRIPTION_RE.test(description)
  ) {
    return empty;
  }

  const performing = new Set();
  const staff = new Set();
  for (const line of description.split(/\r?\n/gu)) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) continue;
    const role = line.slice(0, colonIndex).trim();
    const keys = line
      .slice(colonIndex + 1)
      .split(/\s*(?:,|;|\/|&|\band\b)\s*/iu)
      .map(metadataNameKey)
      .filter(Boolean);
    if (STAFF_ROLE_RE.test(role)) {
      keys.forEach((key) => staff.add(key));
    }
    if (PERFORMING_ROLE_RE.test(role)) {
      keys.forEach((key) => performing.add(key));
    }
  }
  return { performing, staff };
}

function corroboratedPrimaryArtist(info, artists) {
  const providerKeys = [info.uploader, info.channel]
    .map(metadataNameKey)
    .filter(Boolean);
  return artists.find((artist) => providerKeys.includes(artist.key));
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}

function metadataValueContainsArtist(value, artistKey) {
  const normalizedValue = metadataNameKey(value);
  if (!normalizedValue || !artistKey) return false;
  return new RegExp(
    `(?:^|${ARTIST_NAME_BOUNDARY_PATTERN})${escapeRegExp(artistKey)}(?=$|${ARTIST_NAME_BOUNDARY_PATTERN})`,
    'u',
  ).test(normalizedValue);
}

function activeOpeningBracket(text, endIndex) {
  const stack = [];
  for (let index = 0; index < endIndex; index += 1) {
    const character = text[index];
    if (BRACKET_CLOSE_BY_OPEN.has(character)) {
      stack.push({ character, index });
      continue;
    }
    if (
      stack.length > 0 &&
      BRACKET_CLOSE_BY_OPEN.get(stack.at(-1).character) === character
    ) {
      stack.pop();
    }
  }
  return stack.at(-1) || null;
}

function matchingBracketEnd(text, opening) {
  const expectedClosers = [];
  for (let index = opening.index; index < text.length; index += 1) {
    const character = text[index];
    if (BRACKET_CLOSE_BY_OPEN.has(character)) {
      expectedClosers.push(BRACKET_CLOSE_BY_OPEN.get(character));
      continue;
    }
    if (expectedClosers.at(-1) !== character) continue;
    expectedClosers.pop();
    if (expectedClosers.length === 0) return index;
  }
  return text.length;
}

function unbracketedFeatureEnd(text, startIndex) {
  const remainder = text.slice(startIndex);
  const boundaries = [
    /\s[-\u2013\u2014]\s/u.exec(remainder)?.index,
    FEATURE_SUFFIX_BRACKET_RE.exec(remainder)?.index,
  ].filter(Number.isInteger);
  return boundaries.length > 0
    ? startIndex + Math.min(...boundaries)
    : text.length;
}

function featureCreditSections(text) {
  const sections = [];
  for (const match of text.matchAll(FEATURE_MARKER_RE)) {
    const startIndex = match.index + match[0].length;
    const opening = activeOpeningBracket(text, match.index);
    const endIndex = opening
      ? matchingBracketEnd(text, opening)
      : unbracketedFeatureEnd(text, startIndex);
    sections.push(text.slice(startIndex, endIndex));
  }
  return sections;
}

function titleFeaturedArtistKeys(info, artists) {
  const keys = new Set();
  for (const value of [info.track, info.title]) {
    const text = normalizeText(value);
    for (const section of featureCreditSections(text)) {
      artists
        .filter((artist) => metadataValueContainsArtist(section, artist.key))
        .forEach((artist) => keys.add(artist.key));
    }
  }
  return keys;
}

function descriptionPerformingArtistKeys(description, artists) {
  const keys = new Set();
  if (
    typeof description !== 'string' ||
    !AUTO_GENERATED_DESCRIPTION_RE.test(description)
  ) {
    return keys;
  }

  for (const line of description.split(/\r?\n/gu)) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) continue;
    const role = line.slice(0, colonIndex).trim();
    if (!PERFORMING_ROLE_RE.test(role)) continue;
    const value = line.slice(colonIndex + 1);
    artists
      .filter((artist) => metadataValueContainsArtist(value, artist.key))
      .forEach((artist) => keys.add(artist.key));
  }
  return keys;
}

// Auto-generated music descriptions often expose songwriters/producers in the
// same plural `artists` list as the actual performer. Collapse that list only
// when uploader/channel independently corroborates its primary member; explicit
// performing roles and title-level feature credits are the only additions.
function corroboratedAutoGeneratedPerformers(info, artists) {
  if (
    artists.length < 2 ||
    typeof info.description !== 'string' ||
    !AUTO_GENERATED_DESCRIPTION_RE.test(info.description)
  ) {
    return undefined;
  }

  const primary = corroboratedPrimaryArtist(info, artists);
  if (!primary) return undefined;

  const performing = descriptionPerformingArtistKeys(info.description, artists);
  const featured = titleFeaturedArtistKeys(info, artists);
  const performerKeys = new Set([primary.key, ...performing, ...featured]);
  return artists
    .filter((artist) => performerKeys.has(artist.key))
    .map((artist) => artist.text)
    .join(', ');
}

// Phase-one compatibility projection. Keep this exact behavior available to
// Settings maintenance so an originless value written by that release can be
// recognized and safely upgraded without treating arbitrary manual text as a
// provider value.
function artistsWithoutConfirmedStaff(info, artists) {
  if (artists.length < 2) return undefined;
  const primary = corroboratedPrimaryArtist(info, artists);
  if (!primary) return undefined;

  const { performing, staff } = creditRoleKeys(info.description);
  const staffOnlyArtistKeys = new Set(
    artists
      .filter(
        (artist) =>
          artist.key !== primary.key &&
          staff.has(artist.key) &&
          !performing.has(artist.key),
      )
      .map((artist) => artist.key),
  );
  if (staffOnlyArtistKeys.size === 0) return undefined;

  return artists
    .filter((artist) => !staffOnlyArtistKeys.has(artist.key))
    .map((artist) => artist.text)
    .join(', ');
}

function trustedTitleDerivedFields(info, hasStructuredArtist) {
  if (hasStructuredArtist) return null;
  const titleDerived = extractTitleDerivedSearchParts(info.title)[0];
  if (!titleDerived) return null;

  const uploader = normalizeText(info.uploader) || normalizeText(info.channel);
  if (!uploader) return null;
  if (looksLikeChannelArtist(uploader)) return titleDerived;
  const uploaderKey = metadataNameKey(uploader);
  return titleDerived.artistNames?.some(
    (artist) => metadataNameKey(artist) === uploaderKey,
  )
    ? titleDerived
    : null;
}

function selectMusicFields(
  info,
  structuredArtistProjection = corroboratedAutoGeneratedPerformers,
) {
  const structuredTrack = normalizeText(info.track);
  const artists = normalizedStringList(info.artists);
  const singularArtist = normalizeText(info.artist);
  const hasStructuredArtist = Boolean(artists.length > 0 || singularArtist);
  const titleDerived = trustedTitleDerivedFields(info, hasStructuredArtist);
  const artist =
    structuredArtistProjection(info, artists) ||
    (artists.length > 0
      ? artists.map((entry) => entry.text).join(', ')
      : singularArtist ||
        normalizeText(titleDerived?.artistNames?.[0]) ||
        normalizeText(info.uploader) ||
        normalizeText(info.channel) ||
        undefined);

  return {
    title:
      structuredTrack ||
      normalizeText(titleDerived?.trackName) ||
      normalizeText(info.title) ||
      undefined,
    artist,
  };
}

function previousProviderProjection(info) {
  return {
    title: typeof info.title === 'string' ? info.title : undefined,
    artist:
      typeof info.artist === 'string'
        ? info.artist
        : typeof info.uploader === 'string'
          ? info.uploader
          : undefined,
  };
}

function uniqueMetadataProjections(projections) {
  return projections.filter(
    (projection, index) =>
      projections.findIndex(
        (candidate) =>
          candidate.title === projection.title &&
          candidate.artist === projection.artist,
      ) === index,
  );
}

// Shared by downloadAudio (reads a yt-dlp .info.json sidecar) and
// fetchMetadata (reads yt-dlp's --dump-single-json object directly) — same
// yt-dlp info shape either way, so the field-extraction rules must match.
function extractMetadataFields(info) {
  const { title, artist } = selectMusicFields(info);
  const duration =
    Number.isFinite(info.duration) && info.duration > 0
      ? info.duration
      : undefined;
  const thumbnailUrl = extractThumbnailUrl(info);
  // Album fields are optional music metadata; do not invent fallbacks.
  const album = normalizeText(info.album) || undefined;
  const releaseYear =
    Number.isInteger(info.release_year) &&
    info.release_year >= 1000 &&
    info.release_year <= 9999
      ? info.release_year
      : undefined;
  return {
    title,
    artist,
    duration,
    ...(thumbnailUrl ? { thumbnailUrl } : {}),
    ...(album ? { album } : {}),
    ...(releaseYear ? { releaseYear } : {}),
  };
}

function extractMetadataMaintenanceFields(info) {
  return {
    normalized: extractMetadataFields(info),
    previousProjections: uniqueMetadataProjections([
      previousProviderProjection(info),
      selectMusicFields(info, artistsWithoutConfirmedStaff),
    ]),
  };
}

module.exports = {
  isHttpsUrl,
  extractThumbnailUrl,
  extractMetadataFields,
  extractMetadataMaintenanceFields,
};
