'use strict';

const {
  extractTitleDerivedSearchParts,
  looksLikeChannelArtist,
  normalizeText,
} = require('./musicTitle');
const { VIDEO_ID_RE } = require('./youtube');

const AUTO_GENERATED_DESCRIPTION_RE = /\bAuto-generated by YouTube\b/iu;
const STAFF_ROLE_RE =
  /\b(?:arranger|composer|engineer|lyricist|music\s+publisher|producer|songwriter|writer)\b/iu;
const PERFORMING_ROLE_RE = /\b(?:artist|performer|vocalist|vocals?)\b/iu;

function metadataNameKey(value) {
  return normalizeText(value)
    .normalize('NFKC')
    .replace(/\s+/gu, ' ')
    .toLocaleLowerCase();
}

function isHttpsUrl(value) {
  if (typeof value !== 'string') return false;
  try {
    return new URL(value).protocol === 'https:';
  } catch {
    return false;
  }
}

function extractThumbnailUrl(info) {
  if (isHttpsUrl(info.thumbnail)) return info.thumbnail;
  if (Array.isArray(info.thumbnails)) {
    const thumbnailUrl = [...info.thumbnails]
      .reverse()
      .map((thumbnail) => thumbnail?.url)
      .find(isHttpsUrl);
    if (thumbnailUrl) return thumbnailUrl;
  }

  if (typeof info.id === 'string' && VIDEO_ID_RE.test(info.id)) {
    return `https://i.ytimg.com/vi/${info.id}/hqdefault.jpg`;
  }
  return undefined;
}

function normalizedStringList(value) {
  if (!Array.isArray(value)) return [];
  const values = [];
  for (const entry of value) {
    const text = normalizeText(entry);
    const key = metadataNameKey(text);
    if (!key || values.some((current) => current.key === key)) continue;
    values.push({ key, text });
  }
  return values;
}

function creditRoleKeys(description) {
  const empty = { performing: new Set(), staff: new Set() };
  if (
    typeof description !== 'string' ||
    !AUTO_GENERATED_DESCRIPTION_RE.test(description)
  ) {
    return empty;
  }

  const performing = new Set();
  const staff = new Set();
  for (const line of description.split(/\r?\n/gu)) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) continue;
    const role = line.slice(0, colonIndex).trim();
    const keys = line
      .slice(colonIndex + 1)
      .split(/\s*(?:,|;|\/|&|\band\b)\s*/iu)
      .map(metadataNameKey)
      .filter(Boolean);
    if (STAFF_ROLE_RE.test(role)) {
      keys.forEach((key) => staff.add(key));
    }
    if (PERFORMING_ROLE_RE.test(role)) {
      keys.forEach((key) => performing.add(key));
    }
  }
  return { performing, staff };
}

function artistsWithoutConfirmedStaff(info, artists) {
  if (artists.length < 2) return undefined;
  const providerKeys = [info.uploader, info.channel]
    .map(metadataNameKey)
    .filter(Boolean);
  const primary = artists.find((artist) => providerKeys.includes(artist.key));
  if (!primary) return undefined;

  const { performing, staff } = creditRoleKeys(info.description);
  const staffOnlyArtistKeys = new Set(
    artists
      .filter(
        (artist) =>
          artist.key !== primary.key &&
          staff.has(artist.key) &&
          !performing.has(artist.key),
      )
      .map((artist) => artist.key),
  );
  if (staffOnlyArtistKeys.size === 0) return undefined;

  return artists
    .filter((artist) => !staffOnlyArtistKeys.has(artist.key))
    .map((artist) => artist.text)
    .join(', ');
}

function trustedTitleDerivedFields(info, hasStructuredArtist) {
  if (hasStructuredArtist) return null;
  const titleDerived = extractTitleDerivedSearchParts(info.title)[0];
  if (!titleDerived) return null;

  const uploader = normalizeText(info.uploader) || normalizeText(info.channel);
  if (!uploader) return null;
  if (looksLikeChannelArtist(uploader)) return titleDerived;
  const uploaderKey = metadataNameKey(uploader);
  return titleDerived.artistNames?.some(
    (artist) => metadataNameKey(artist) === uploaderKey,
  )
    ? titleDerived
    : null;
}

function selectMusicFields(info) {
  const structuredTrack = normalizeText(info.track);
  const artists = normalizedStringList(info.artists);
  const singularArtist = normalizeText(info.artist);
  const hasStructuredArtist = Boolean(artists.length > 0 || singularArtist);
  const titleDerived = trustedTitleDerivedFields(info, hasStructuredArtist);
  const artist =
    artistsWithoutConfirmedStaff(info, artists) ||
    (artists.length > 0
      ? artists.map((entry) => entry.text).join(', ')
      : singularArtist ||
        normalizeText(titleDerived?.artistNames?.[0]) ||
        normalizeText(info.uploader) ||
        normalizeText(info.channel) ||
        undefined);

  return {
    title:
      structuredTrack ||
      normalizeText(titleDerived?.trackName) ||
      normalizeText(info.title) ||
      undefined,
    artist,
  };
}

function previousProviderProjection(info) {
  return {
    title: typeof info.title === 'string' ? info.title : undefined,
    artist:
      typeof info.artist === 'string'
        ? info.artist
        : typeof info.uploader === 'string'
          ? info.uploader
          : undefined,
  };
}

// Shared by downloadAudio (reads a yt-dlp .info.json sidecar) and
// fetchMetadata (reads yt-dlp's --dump-single-json object directly) — same
// yt-dlp info shape either way, so the field-extraction rules must match.
function extractMetadataFields(info) {
  const { title, artist } = selectMusicFields(info);
  const duration =
    Number.isFinite(info.duration) && info.duration > 0
      ? info.duration
      : undefined;
  const thumbnailUrl = extractThumbnailUrl(info);
  // Album fields are optional music metadata; do not invent fallbacks.
  const album = normalizeText(info.album) || undefined;
  const releaseYear =
    Number.isInteger(info.release_year) &&
    info.release_year >= 1000 &&
    info.release_year <= 9999
      ? info.release_year
      : undefined;
  return {
    title,
    artist,
    duration,
    ...(thumbnailUrl ? { thumbnailUrl } : {}),
    ...(album ? { album } : {}),
    ...(releaseYear ? { releaseYear } : {}),
  };
}

function extractMetadataMaintenanceFields(info) {
  return {
    normalized: extractMetadataFields(info),
    previousProjection: previousProviderProjection(info),
  };
}

module.exports = {
  isHttpsUrl,
  extractThumbnailUrl,
  extractMetadataFields,
  extractMetadataMaintenanceFields,
};
