import { describe, it, expect } from 'vitest';
import {
  extractMetadataFields,
  extractMetadataMaintenanceFields,
} from './ytdlpInfo.js';

describe('extractMetadataFields', () => {
  it('returns the normalized projection beside the previous provider projection for maintenance', () => {
    expect(
      extractMetadataMaintenanceFields({
        title: ' Blue Blood ',
        track: 'Blue Blood',
        artist: ' IVE, Nick Hahn ',
        artists: ['IVE', 'Nick Hahn'],
        uploader: 'IVE',
        description: ['Producer: Nick Hahn', 'Auto-generated by YouTube.'].join(
          '\n',
        ),
        duration: 167,
      }),
    ).toEqual({
      normalized: {
        title: 'Blue Blood',
        artist: 'IVE',
        duration: 167,
      },
      previousProjections: [
        {
          title: ' Blue Blood ',
          artist: ' IVE, Nick Hahn ',
        },
        {
          title: 'Blue Blood',
          artist: 'IVE',
        },
      ],
    });
  });

  it('rejects invalid supplemental scalar values', () => {
    expect(
      extractMetadataFields({
        title: 'Song',
        uploader: 'Artist',
        duration: -1,
        album: '   ',
        release_year: 20,
      }),
    ).toEqual({
      title: 'Song',
      artist: 'Artist',
      duration: undefined,
    });
  });

  it('projects a finite non-negative YouTube view count without coercion', () => {
    expect(
      extractMetadataFields({
        title: 'Song',
        uploader: 'Artist',
        duration: 211,
        view_count: 123456789,
      }),
    ).toMatchObject({ viewCount: 123456789 });

    for (const view_count of [-1, Number.POSITIVE_INFINITY, '123456789']) {
      expect(
        extractMetadataFields({ title: 'Song', view_count }),
      ).not.toHaveProperty('viewCount');
    }
  });

  it('prefers structured track and plural artists from a YT Music album entry', () => {
    expect(
      extractMetadataFields({
        title: 'Decorated upload title',
        track: '晩餐歌 - Bansanka',
        artist: 'stale singular artist',
        artists: ['tuki.'],
        uploader: 'tuki.(17)',
        duration: 218,
      }),
    ).toEqual({
      title: '晩餐歌 - Bansanka',
      artist: 'tuki.',
      duration: 218,
    });
  });

  it('does not mistake a translated YT Music flat-playlist title for Artist - Title', () => {
    expect(
      extractMetadataFields({
        title: '晩餐歌 - Bansanka',
        uploader: 'tuki.(17)',
        duration: 218,
      }),
    ).toEqual({
      title: '晩餐歌 - Bansanka',
      artist: 'tuki.(17)',
      duration: 218,
    });
  });

  it('keeps a genuine multi-artist YT Music collaboration', () => {
    expect(
      extractMetadataFields({
        title: 'Dawn',
        track: 'Dawn',
        artist: 'SAYURI, MY FIRST STORY',
        artists: ['SAYURI', 'MY FIRST STORY'],
        uploader: '酸欠少女 さユり(Sanketsu-girl Sayuri)',
        description: [
          'Provided to YouTube by Sony Music Labels Inc.',
          '',
          'Dawn · SAYURI · MY FIRST STORY',
          '',
          'Lyricist: Hiro',
          'Composer: Sho',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 241,
      }),
    ).toEqual({
      title: 'Dawn',
      artist: 'SAYURI, MY FIRST STORY',
      duration: 241,
    });
  });

  it('uses the corroborated primary artist when an auto-generated artist list contains staff', () => {
    const info = {
      title: 'Blue Blood',
      track: 'Blue Blood',
      artist: 'IVE, Seo Ji Eum, Nick Hahn, Sophia Brenan, Elle Campbell',
      artists: [
        'IVE',
        'Seo Ji Eum',
        'Nick Hahn',
        'Sophia Brenan',
        'Elle Campbell',
      ],
      uploader: 'IVE',
      channel: 'IVE',
      description: [
        'Provided to YouTube by The Orchard Enterprises',
        '',
        'Blue Blood · IVE · Seo Ji Eum · Nick Hahn · Sophia Brenan · Elle Campbell',
        '',
        'Producer: Nick Hahn',
        'Recording Engineer: Grace Yang',
        'Auto-generated by YouTube.',
      ].join('\n'),
      duration: 167,
    };

    expect(extractMetadataFields(info)).toEqual({
      title: 'Blue Blood',
      artist: 'IVE',
      duration: 167,
    });
    expect(
      extractMetadataMaintenanceFields(info).previousProjections,
    ).toContainEqual({
      title: 'Blue Blood',
      artist: 'IVE, Seo Ji Eum, Sophia Brenan, Elle Campbell',
    });
  });

  it.each([
    ['I AM', ['IVE', 'Kim Ina', 'RYAN JHUN', 'Kristrin Marie Skolem']],
    ['Kitsch', ['IVE', 'Lee Seu Ran', 'Hwang Hyun(MonoTree)', 'Lise Reppe']],
  ])(
    'projects the auto-generated IVE album track %s to its corroborated performer',
    (track, artists) => {
      expect(
        extractMetadataFields({
          title: track,
          track,
          artist: artists.join(', '),
          artists,
          uploader: 'IVE',
          channel: 'IVE',
          description: 'Auto-generated by YouTube.',
          duration: 180,
        }).artist,
      ).toBe('IVE');
    },
  );

  it('does not collapse collaborators from an untrusted free-form description', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'Guest Artist'],
        uploader: 'Lead Artist',
        description: 'Producer: Guest Artist',
        duration: 180,
      }).artist,
    ).toBe('Lead Artist, Guest Artist');
  });

  it('keeps an auto-generated collaborator explicitly credited as a performer', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'Guest Artist'],
        uploader: 'Lead Artist',
        description: [
          'Producer, Associated Performer: Guest Artist',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 180,
      }).artist,
    ).toBe('Lead Artist, Guest Artist');
  });

  it('keeps a confirmed performer while removing a separate staff-only artist entry', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'Guest Artist', 'Studio Person'],
        uploader: 'Lead Artist',
        description: [
          'Associated Performer: Guest Artist',
          'Producer: Studio Person',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 180,
      }).artist,
    ).toBe('Lead Artist, Guest Artist');
  });

  it('drops an unclassified artist-list member without performer evidence', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'Guest Artist', 'Studio Person'],
        uploader: 'Lead Artist',
        description: [
          'Producer: Studio Person',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 180,
      }).artist,
    ).toBe('Lead Artist');
  });

  it('keeps a collaborator credited as both producer and performer on separate lines', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'Guest Artist'],
        uploader: 'Lead Artist',
        description: [
          'Producer: Guest Artist',
          'Associated Performer: Guest Artist',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 180,
      }).artist,
    ).toBe('Lead Artist, Guest Artist');
  });

  it('does not treat an unrelated staff credit as collaborator evidence', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'Guest Artist'],
        uploader: 'Lead Artist',
        description: [
          'Producer: Studio Person',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 180,
      }).artist,
    ).toBe('Lead Artist');
  });

  it('keeps an artist-list member named by a feat marker in the track title', () => {
    expect(
      extractMetadataFields({
        title: 'Shared Stage (feat. Guest Artist)',
        track: 'Shared Stage (feat. Guest Artist)',
        artists: ['Lead Artist', 'Guest Artist', 'Unclassified Name'],
        uploader: 'Lead Artist',
        description: 'Auto-generated by YouTube.',
        duration: 180,
      }).artist,
    ).toBe('Lead Artist, Guest Artist');
  });

  it.each([
    ['Shared Stage (feat. Simon & Garfunkel)', 'Simon & Garfunkel'],
    ['Shared Stage (feat. X Ambassadors)', 'X Ambassadors'],
    ['Shared Stage (feat. Guest Artist) (Official Audio)', 'Guest Artist'],
    ['Shared Stage feat. Guest Artist (Official Audio)', 'Guest Artist'],
    ['Shared Stage（feat. Guest Artist）', 'Guest Artist'],
    ['Shared Stage feat. Guest Artist - Remastered', 'Guest Artist'],
    ['Shared Stage (feat. (G)I-DLE)', '(G)I-DLE'],
    ['Shared Stage (feat. Hwang Hyun(MonoTree))', 'Hwang Hyun(MonoTree)'],
    ['Shared Stage (feat. tuki.(17))', 'tuki.(17)'],
  ])('keeps the complete featured artist in %s', (track, featuredArtist) => {
    expect(
      extractMetadataFields({
        title: track,
        track,
        artists: ['Lead Artist', featuredArtist, 'Unclassified Name'],
        uploader: 'Lead Artist',
        description: 'Auto-generated by YouTube.',
        duration: 180,
      }).artist,
    ).toBe(`Lead Artist, ${featuredArtist}`);
  });

  it('keeps a complete performer name containing a slash', () => {
    expect(
      extractMetadataFields({
        track: 'Shared Stage',
        artists: ['Lead Artist', 'AC/DC', 'Unclassified Name'],
        uploader: 'Lead Artist',
        description: [
          'Associated Performer: AC/DC',
          'Auto-generated by YouTube.',
        ].join('\n'),
        duration: 180,
      }).artist,
    ).toBe('Lead Artist, AC/DC');
  });

  it.each([
    'Shared Stage (feat. Guest Artist) (David Guetta Remix)',
    'Shared Stage feat. Guest Artist - David Guetta Remix',
  ])(
    'does not include a named remixer after the feat section in %s',
    (track) => {
      expect(
        extractMetadataFields({
          title: track,
          track,
          artists: ['Lead Artist', 'Guest Artist', 'David Guetta'],
          uploader: 'Lead Artist',
          description: 'Auto-generated by YouTube.',
          duration: 180,
        }).artist,
      ).toBe('Lead Artist, Guest Artist');
    },
  );

  it('derives track and artist from an ordinary YouTube MV title before using a label uploader', () => {
    expect(
      extractMetadataFields({
        title: '劉若英 René Liu【後來 Later】Official Music Video',
        uploader: '滾石唱片 ROCK RECORDS',
        duration: 341,
      }),
    ).toEqual({
      title: '後來 Later',
      artist: '劉若英 René Liu',
      duration: 341,
    });
  });

  it('does not derive Artist - Title without uploader or channel evidence', () => {
    expect(
      extractMetadataFields({
        title: 'Lecture One - Introduction',
        duration: 600,
      }),
    ).toEqual({
      title: 'Lecture One - Introduction',
      artist: undefined,
      duration: 600,
    });
  });

  it('derives a missing artist when structured track metadata and label evidence coexist', () => {
    expect(
      extractMetadataFields({
        track: 'Parachute',
        title: 'Sabrina Hu - Parachute (Official Music Video)',
        uploader: 'Example Music',
        duration: 240,
      }),
    ).toEqual({
      title: 'Parachute',
      artist: 'Sabrina Hu',
      duration: 240,
    });
  });

  it('extracts a full YT Music info object', () => {
    expect(
      extractMetadataFields({
        title: '夜に駆ける',
        artist: 'YOASOBI',
        uploader: 'YOASOBI Official Channel',
        duration: 261,
      }),
    ).toEqual({ title: '夜に駆ける', artist: 'YOASOBI', duration: 261 });
  });

  it('falls back to uploader for artist on a plain YouTube upload', () => {
    expect(
      extractMetadataFields({
        title: 'Some Video',
        uploader: 'Some Channel',
        duration: 120.5,
      }),
    ).toEqual({ title: 'Some Video', artist: 'Some Channel', duration: 120.5 });
  });

  it('leaves artist undefined when neither artist nor uploader is present', () => {
    expect(extractMetadataFields({ title: 'Untitled', duration: 10 })).toEqual({
      title: 'Untitled',
      artist: undefined,
      duration: 10,
    });
  });

  it('leaves everything undefined for an empty info object', () => {
    expect(extractMetadataFields({})).toEqual({
      title: undefined,
      artist: undefined,
      duration: undefined,
    });
  });

  it('ignores wrong-typed fields instead of coercing them', () => {
    expect(
      extractMetadataFields({ title: 123, artist: null, duration: '261' }),
    ).toEqual({ title: undefined, artist: undefined, duration: undefined });
  });

  it('extracts a direct HTTPS thumbnail URL for preview-only rendering', () => {
    expect(
      extractMetadataFields({
        title: 'Preview Song',
        thumbnail: 'https://i.ytimg.com/vi/id/hqdefault.jpg',
      }).thumbnailUrl,
    ).toBe('https://i.ytimg.com/vi/id/hqdefault.jpg');
  });

  it('uses the largest thumbnail array entry when no direct thumbnail exists', () => {
    expect(
      extractMetadataFields({
        thumbnails: [
          { url: 'https://i.ytimg.com/vi/id/default.jpg' },
          { url: 'https://i.ytimg.com/vi/id/maxresdefault.jpg' },
        ],
      }).thumbnailUrl,
    ).toBe('https://i.ytimg.com/vi/id/maxresdefault.jpg');
  });

  it('falls back to the standard YouTube thumbnail URL for video ids', () => {
    expect(
      extractMetadataFields({
        id: '0D28qd--kRE',
      }).thumbnailUrl,
    ).toBe('https://i.ytimg.com/vi/0D28qd--kRE/hqdefault.jpg');
  });

  it('ignores non-HTTPS thumbnail URLs', () => {
    expect(
      extractMetadataFields({
        thumbnail: 'file:///C:/secret.jpg',
        thumbnails: [{ url: 'http://example.test/insecure.jpg' }],
      }).thumbnailUrl,
    ).toBeUndefined();
  });

  it('extracts album and releaseYear for a recognized-music source', () => {
    const fields = extractMetadataFields({
      title: 'Track Name',
      artist: 'Some Artist',
      album: 'Some Album',
      release_year: 2018,
    });
    expect(fields.album).toBe('Some Album');
    expect(fields.releaseYear).toBe(2018);
  });

  it('omits album and releaseYear rather than defaulting when absent', () => {
    const fields = extractMetadataFields({
      title: 'Plain Upload',
      uploader: 'Some Channel',
    });
    expect(fields.album).toBeUndefined();
    expect(fields.releaseYear).toBeUndefined();
  });

  it('ignores wrong-typed album/release_year instead of coercing them', () => {
    const fields = extractMetadataFields({
      title: 'Track Name',
      album: 123,
      release_year: '2018',
    });
    expect(fields.album).toBeUndefined();
    expect(fields.releaseYear).toBeUndefined();
  });
});
